include:
  - board: nice_nano
    shield: sweep_dongle
    snippet: zmk-usb-logging
  - board: nice_nano
    shield: settings_reset
  - board: nice_nano
    shield: sweep_left
    snippet: zmk-usb-logging
  - board: nice_nano
    shield: sweep_right
    snippet: zmk-usb-logging
