include:
  - board: nice_nano_v2
    shield: sweep_dongle
  - board: nice_nano_v2
    shield: settings_reset
  - board: nice_nano_v2
    shield: sweep_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano_v2
    shield: sweep_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
