include:
  - board: nice_nano
    shield: sweep_dongle
    snippet: zmk-usb-logging
  - board: nice_nano
    shield: settings_reset
  - board: nice_nano
    shield: sweep_left
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  - board: nice_nano
    shield: sweep_right
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
